approval_policy = "untrusted"
sandbox_mode = "workspace-write"

[features]
web_search_request = true

[sandbox_workspace_write]
network_access = true

# -- Waiting Prj Suport --
# [mcp_servers.serena]
# command = "uvx"
# args = [
#   "--from",
#   "git+https://github.com/oraios/serena",
#   "serena",
#   "start-mcp-server",
#   "--project",
#   "XXXXXXXX"
# ]
#
# [mcp_servers.backlog]
# command = "npx"
# args = [
#   "backlog-mcp-server"
# ]
# env = { BACKLOG_DOMAIN = "XXXXXXXX", BACKLOG_API_KEY = "XXXXXXXX" }

